{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-stack.secretName" . }}
  labels:
    {{- include "matrix-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ required "secrets.data.dbPassword is required when secrets.create=true" .Values.secrets.data.dbPassword | quote }}
  matrix-admin-password: {{ required "secrets.data.matrixAdminPassword is required when secrets.create=true" .Values.secrets.data.matrixAdminPassword | quote }}
  registration-shared-secret: {{ required "secrets.data.registrationSharedSecret is required when secrets.create=true" .Values.secrets.data.registrationSharedSecret | quote }}
  {{- if .Values.smtp.enabled }}
  smtp-user: {{ required "secrets.data.smtpUser is required when secrets.create=true" .Values.secrets.data.smtpUser | quote }}
  smtp-password: {{ required "secrets.data.smtpPassword is required when secrets.create=true" .Values.secrets.data.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.coturn.enabled }}
  turn-password: {{ required "secrets.data.turnPassword is required when secrets.create=true" .Values.secrets.data.turnPassword | quote }}
  {{- end }}
  homeserver.signing.key: {{ required "secrets.data.synapseSigningKey is required when secrets.create=true" .Values.secrets.data.synapseSigningKey | quote }}
{{- end }}
