apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-stack.fullname" . }}-element-config
  labels:
    {{- include "matrix-stack.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": {{ .Values.urls.matrixBase | quote }},
          "server_name": {{ .Values.domains.matrix | quote }}
        }
      },
      "brand": {{ .Values.app.brand | quote }},
      "default_theme": {{ .Values.element.theme | quote }},
      "show_labs_settings": {{ .Values.element.showLabsSettings }}
    }
---
{{- if .Values.ketesa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-stack.fullname" . }}-ketesa-config
  labels:
    {{- include "matrix-stack.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "restrictBaseUrl": {{ .Values.urls.ketesaBase | quote }},
      "wellKnownDiscovery": false
    }
{{- end }}
