apiVersion: v1
kind: Secret
metadata:
  name: matrix-stack-secrets
  namespace: matrix
type: Opaque
stringData:
  db-password: CHANGE_ME_DB_PASSWORD
  matrix-admin-password: CHANGE_ME_MATRIX_ADMIN_PASSWORD
  registration-shared-secret: CHANGE_ME_REGISTRATION_SHARED_SECRET
  smtp-user: CHANGE_ME_SMTP_USER
  smtp-password: CHANGE_ME_SMTP_PASSWORD
  turn-password: CHANGE_ME_TURN_PASSWORD
  homeserver.signing.key: |
    CHANGE_ME_COPY_EXISTING_SYNAPSE_SIGNING_KEY_DO_NOT_GENERATE_A_NEW_ONE
